snake_ai
andreamper220/snakeai pull request #1
Opened 2024-06-21 12:15 UTC by andreamper220

2024-06-22 17:11 UTC, gonozov0 requested changes
Отличная работа 💪
Довольно продуктивно поработал и много кода написал
Оставил пару комментов по улучшению кода
Для сдачи еще как минимум не хаватает inmemory стораджей и тестов

Если есть время и желание, то я рекомендую пересмотреть структуру твоего кода, сейчас вижу небольшой хаос, в моем понимании любой приличный проект должен быть в internal разделен на 3 слоя:
- публичный слой (в ddd - application, тут как раз инициализация http сервера, ручек, логика хендлеров и т.д.)
- слой бизнес логики (domain, тут все основные структуры, которые инкапсулируют бизнес логику твоего приложения, важно что этот слой ничего не знает про другие слои, со слоем infrastructure связан только через абстракции/интерфейсы)
- внешние клиенты и бд (infrastructure, тут все клиенты к внешним системам, страджи для баз данных и главное inmemory реализация для каждого, которая используется в тестах)

2024-06-22 17:11 UTC, gonozov0 commented on env.d/docker.d/Dockerfile
Почему все файлы заканчиваются на ".d"? На мой взгляд странно, что докерфайл находится в env директории

2024-06-22 17:11 UTC, gonozov0 commented on internal/server/ai/ai.go
Выглядит как что-то не доделанное

2024-06-22 17:11 UTC, gonozov0 commented on internal/server/ai/data/game.go
> +								break
такую вложенность очень сложно воспринимать, перепиши код в другом стиле
```go
	for _, g := range CurrentGames.Games {
		if g == nil {
			continue
		}
		pa := g.Party
		....
```

2024-06-22 17:11 UTC, gonozov0 commented on internal/server/ai/data/game.go
> +								break
Ну и вообще довольно странно, что у тебя слайс может состоять из nil

2024-06-22 17:11 UTC, gonozov0 commented on internal/server/handlers/delete_handlers/player.go
> +				for _, s := range g.Snakes {
Тут довольно большая алгоритмическая сложность, я бы пересмотрел структуры хранению в пользу мапов

2024-06-22 17:11 UTC, gonozov0 commented on internal/shared/helper.go
а shared между какими другими пакетами? у тебя весь этот пакет используется только в server и в основном это реальная бизнес логика

2024-06-22 17:11 UTC, gonozov0 commented on internal/logger/logger.go
это можно вынести в pkg

2024-06-23 10:42 UTC, andreamper220 commented on env.d/docker.d/Dockerfile
директории заканчиваются на .d, т.к. это может быть расшифровано по-разному: 'dist' / 'dev' / 'deps', и для всех значений файлы будут удовлетворять своим содержимым :)

2024-06-24 11:44 UTC, gonozov0 approved these changes
Отличная работа 👍
Все моменты поправлены

2024-06-24 12:45 UTC, merged